use adw::prelude::*;
use glib::{Object, clone};
use gtk::{
    CompositeTemplate,
    glib::{self, closure_local},
    subclass::prelude::*,
};

use crate::{
    preferences::output_config::{audio_format_row::AudioFormatRow}, server::AudioFormatConfig,
};

mod imp {
    use std::cell::OnceCell;

    use adw::subclass::{action_row::ActionRowImpl, preferences_row::PreferencesRowImpl};

    use super::*;

    #[derive(Default, CompositeTemplate)]
    #[template(resource = "/io/github/htkhiem/Euphonica/gtk/preferences/audio-format-box.ui")]
    pub struct AudioFormatBox {
        #[template_child]
        pub enabled: TemplateChild<adw::SwitchRow>,
        #[template_child]
        pub listbox: TemplateChild<gtk::ListBox>,
        #[template_child]
        pub add: TemplateChild<gtk::Button>,
        pub key: OnceCell<&'static str>,
    }

    // The central trait for subclassing a GObject
    #[glib::object_subclass]
    impl ObjectSubclass for AudioFormatBox {
        // `NAME` needs to match `class` attribute of template
        const NAME: &'static str = "EuphonicaAudioFormatBox";
        type Type = super::AudioFormatBox;
        type ParentType = gtk::Box;

        fn class_init(klass: &mut Self::Class) {
            klass.bind_template();
        }

        fn instance_init(obj: &glib::subclass::InitializingObject<Self>) {
            obj.init_template();
        }
    }

    impl ObjectImpl for AudioFormatBox {
        fn constructed(&self) {
            self.parent_constructed();
            self.add.connect_clicked(clone!(
                #[weak(rename_to = this)]
                self,
                move |_| {
                    this.obj().add(&AudioFormatConfig::default());
                }
            ));
        }
    }

    impl WidgetImpl for AudioFormatBox {}
    impl BoxImpl for AudioFormatBox {}
}

glib::wrapper! {
    pub struct AudioFormatBox(ObjectSubclass<imp::AudioFormatBox>)
    @extends gtk::Box, gtk::Widget,
    @implements gtk::Accessible, gtk::Buildable, gtk::ConstraintTarget, gtk::Orientable;
}

impl AudioFormatBox {
    pub fn new(key: &'static str, config: &str, title: &str, subtitle: &str) -> Self {
        let res: Self = Object::builder().build();
        let _ = res.imp().key.set(key);
        // Config string is a space-separated list of audio format substrings.
        for format in config.split_whitespace() {
            if let Ok(format_config) = AudioFormatConfig::try_from(format) {
                res.add(&format_config);
            }
            // For now silently skip malformed substrings (only meant to parse config files generated by us anyway).
        }
        res.imp().enabled.set_title(title);
        res.imp().enabled.set_subtitle(subtitle);
        res
    }

    pub fn update_indices(&self) {
        if let Some(first) = self.imp().listbox.first_child() {
            let mut cursor: gtk::ListBoxRow = first.downcast().unwrap();
            loop {
                let child: AudioFormatRow = cursor.child().and_downcast().unwrap();
                child.update_index();
                if let Some(next) = cursor.next_sibling().and_downcast() {
                    cursor = next;
                } else {
                    break;
                }
            }
        }
    }

    pub fn add(&self, format_config: &AudioFormatConfig) {
        let format_row = AudioFormatRow::from_format(&format_config);
        let row = gtk::ListBoxRow::builder()
            .activatable(false)
            .child(&format_row)
            .build();
        format_row.bind_parent(&row);
        format_row.connect_closure(
            "delete-clicked",
            false,
            closure_local!(
                #[weak(rename_to = this)]
                self,
                move |_: &AudioFormatRow, idx: i32| {
                    if idx >= 0
                        && let Some(row) = this.imp().listbox.row_at_index(idx).as_ref()
                    {
                        this.imp().listbox.remove(row);
                        this.update_indices();
                    }
                }
            ),
        );
        self.imp().listbox.append(&row);
        format_row.update_index();
    }

    pub fn generate_config(&self) -> Option<(&'static str, String)> {
        if self.imp().enabled.is_active() {
            let mut formats: Vec<String> = Vec::new();
            if let Some(first) = self.imp().listbox.first_child() {
                let mut cursor: gtk::ListBoxRow = first.downcast().unwrap();
                loop {
                    let child: AudioFormatRow = cursor.child().and_downcast().unwrap();
                    formats.push(child.generate_config().to_string());
                    if let Some(next) = cursor.next_sibling().and_downcast() {
                        cursor = next;
                    } else {
                        break;
                    }
                }
            }
            if formats.is_empty() {
                None
            } else {
                Some((
                    self.imp()
                        .key
                        .get()
                        .cloned()
                        .unwrap_or_else(|| "allowed_formats"),
                    formats.join(" "),
                ))
            }
        } else {
            None
        }
    }
}